info:
  profile: ${SPRING_PROFILE:local}
  name: @project.name@
  version: @project.version@

spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: DATAMANAGER
  datasource:
    name: datamanger
    username: ${POSTGRES_CON_USERNAME:postgres}
    password: ${POSTGRES_CON_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/application}
    driver-class-name: org.postgresql.Driver
    data:
      jpa:
        database: POSTGRES
        database-platform: POSTGRES
      jta:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: local
    default-schema: dmg
    drop-first: false
    user: ${POSTGRES_MAN_USERNAME:postgres}
    password: ${POSTGRES_MAN_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/application}
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - TRACE
      - CONNECT
    allowed-headers:
      - Authorization
      - Content-Type
    allow-credentials: true
    max-age: 3600